namespace Elgin.Entities.Enums.ResultCodes
{
    public enum Tef_Erro_Android { TEF_PIN_PAD_NAO_ENCONTRADO = -5, TEF_CANCELADO_OPERADOR = -8, TEF_CANCELADO_SERVER = -10, TEF_CANCELADO_SISTEMA = -11 }

    public enum GER_Erro_Conexao
    {
        TIPO_INVALIDO = -2, MODELO_INVALIDO = -3, PORTA_FECHADA = -4, CONEXAO_NEGADA = -5,
        CONEXAO_ATIVA = -6
    }

    public enum GER_Erro_Conexao_Serial
    {
        BAUDRATE_INVALIDO = -11, DISPOSITIVO_NAO_EXISTE = -12, PERMISSAO_NEGADA = -13, ERRO_SERIAL_DESCONHECIDO = -14,
        DISPOSITIVO_JA_ESTA_ABERTO = -15, RECURSO_INDISPONIVEL = -16, OPERACAO_NAO_SUPORTADA = -17, SERIAL_TIMEOUT = -18,
        DISPOSITIVO_REMOVIDO_INESPERADAMENTE = -19
    }

    public enum GER_Erro_Conexao_USB { DISPOSITIVO_NAO_ENCONTRADO = -21, ERRO_DE_ABERTURA_PORTA_USB = -22, ERRO_CLAIM_UL = -23 }

    public enum GER_Erro_Conexao_TCP { PORTA_TCP_INVALIDA = -31 }

    public enum IMP_Erro_Escrita_Impressora { POSICAO_INVALIDA = -41, STILO_INVALIDO = -42, TAMANHO_INVALIDO = -43, ERRO_ESCRITA = -44 }

    public enum IMP_Erro_QRCode { TAMANHO_QR_INVALIDO = -51, NIVEL_DE_CORRECAO_INVALIDO = -52, DADOS_QR_INVALIDOS = -53 }

    public enum IMP_Erro_CodigoBarras
    {
        CB_ALTURA_INVALIDA = -61, CB_LARGURA_INVALIDA = -62, CB_HRI_INVALIDO = -63, CB_TIPO_INVALIDO = -64,
        CB_DADOS_INVALIDOS = -65, CB_AREA_DE_IMPRESSAO_EXCEDIDA = -66
    }

    public enum IMP_Erro_ValidacaoXML { ERRO_XSD = -71, XSD_NAO_ENCONTRADO = -72 }

    public enum IMP_Erro_Leitura_Impressora { NENHUM_DADO_RETORNADO = -81, FALHA_AO_ABRIR_ARQUIVO = -82 }

    public enum IMP_Erro_ValidacaoXMLSAT
    {
        ASSINATURA_QRCODE_INVALIDA = -91, DADOS_XML_VAZIO = -92, DADOS_XML_INVALIDO = -93, ARQUIVO_XML_NAO_PODE_SER_ABERTO = -94,
        ARQUIVO_XML_NAO_CONTEM_DADOS = -95
    }

    public enum IMP_Erro_ValidacaoXMLNFCe
    {
        VERSAO_XMLNFCE_NAO_SUPORTADA = -101, VERSAO_XMLNFCE_INDEFINIDA = -102, TIPO_EMISSAO_INDEFINIDA = -103, PARAMETRO_CONF_INVALIDO = -104,
        ARQUIVO_XML_NFCE_NAO_PODE_SER_ABERTO = -105
    }

    public enum IMP_Erro_Emissao_Sinal_Sonoro { QUANTIDADE_FORA_INTERVALO = -111, TEMPO_FORA_LIMITE = -112 }

    public enum IMP_Erro_Abertura_Gaveta { PINO_INVALIDO = -121, TEMPO_INVALIDO = -122 }

    public enum IMP_Erro_Status { STATUS_NAO_SUPORTADO = -126, PARAMETRO_TIPO_STATUS_INVALIDO = -127 }

    public enum IMP_Erro_Imagem { KEY_INVALIDO = -131, SCALA_INVALIDA = -132 }

    public enum IMP_Erro_ModoPagina { DIRECAO_INVALIDA = -136, POS_IMP_HORIZONTAL_INVALIDA = -137 }

    public enum Erro_Sistema
    {
        NAO_FOI_POSSIVEL_INICIAR_O_SERVICO = -150, ERRO_AO_CARREGAR_BIBLIOTECA_DA_IMPRESSORA = -151, ERRO_AO_CARREGAR_BIBLIOTECA_DO_SAT = -152, ERRO_AO_CARREGAR_BIBLIOTECA_DO_E1SAT = -153,
        OPERACAO_INVALIDA = -154, SERVICO_OCUPADO = -155, ERRO_AO_CARREGAR_BIBLIOTECA_DA_ETIQUETA = -156, BIBLIOTECA_DO_SAT_INVALIDA = -157
    }

    public enum Erro_EnvioComandos
    {
        COMANDO_INVALIDO = -160, ARQUIVO_NAO_EXISTE = -161, ESTE_JSON_NAO_E_UM_OBJETO = -162, TIPO_PARAMETRO_INVALIDO = -163,
        QUANTIDADE_INVALIDA = -164, PARAMETRO_NAO_ENCONTRADO = -165, MODULO_FUNCAO_NAO_ENCONTRADO = -166
    }

    public enum Erro_ConexaoAndroid
    {
        RECONEXOES_ESGOTADAS = -171, CONEXAO_ATIVA_OUTRO = -172, ERRO_ABERTURA_PORTA = -173, ERRO_FECHAMENTO_PORTA = -174,
        ERRO_ESCRITA_PORTA = -175, ERRO_NENHUM_BYTE_ENVIADO = -176, ERRO_LEITURA_PORTA = -177, THREAD_EXECUTION_EXCEPTION = -178,
        THREAD_INTERRUPTED_EXCEPTION = -179, ERRO_NOT_ACTIVITY = -180, MAC_ADDRESS_INVALIDO = -391, DISPOSITIVO_NAO_SUPORTA_BT = -392,
        BLUETOOTH_DESATIVADO = -393, DISPOSITIVO_NAO_PAREADO = -394, ERRO_CONEXAO_BLUETOOTH = -395
    }

    public enum Erro_Outros
    {
        ERRO_FUNCAO_NAO_SUPORTADA = -401, ERRO_ID_INVALIDO = -402, ERRO_SERVICO_NAO_INICIADO = -403, ERRO_ABERTURA_NAO_AUTORIZADA = -404,
        ERRO_FECHAMENTO_NAO_AUTORIZADO = -405, ERRO_FUNCAO_NAO_CHAMADA_PELO_SERVICO = -406, ERRO_FUNCAO_NAO_DISPONIVEL_VIA_SERVICO = -407, ERRO_ACTIVITY_NAO_DEFINIDA = -408
    }

    public enum IMP_Erro_PDF417
    {
        NUMBER_COLUMNS_INVALIDO = -411, NUMBER_ROWS_INVALIDO = -412, WIDTH_INVALIDO = -413, HEIGHT_INVALIDO = -414,
        ERROR_CORRECTION_LEVEL_INVALIDO = -415, OPTIONS_INVALIDO = -416, DADOS_PDF_INVALIDOS = -417, ERRO_PDF_DESCONHECIDO = -418
    }

    public enum GER_Erro_SystemSetting
    {
        ERRO_ALTURA_GAP = -181, ERRO_TIPO_TRANSFERENCIA = -182, ERRO_BAUDRATE_BAUDRATE = -183, ERRO_BAUDRATE_DATA_LENGTH = -184,
        ERRO_BAUDRATE_PARITY = -185, ERRO_BAUDRATE_STOP_BIT = -186, ERRO_SYMBOL = -187
    }

    public enum GER_Erro_SystemLevel
    {
        ERRO_MEDIDA = -191, ERRO_BACKFEED = -192, ERRO_PRINT_ST_POS = -193, ERRO_SENSOR = -194,
        ERRO_MODO_CONTINUO = -195, ERRO_LENGTH = -196, ERRO_MEMORY_STATUS_TIPO_DADOS = -198, ERRO_LIMPA_MODULO_MODULO = -199,
        ERRO_ENVIA_IMAGEM_MODULO = -200, ERRO_ENVIA_IMAGEM_FORMATO = -201, ERRO_ENVIA_IMAGEM_NOME_TAMANHO = -202, ERRO_ENVIA_IMAGEM_NOME_CARACTERE = -203,
        ERRO_ENVIA_IMAGEM_ARQUIVO = -204, ERRO_EXCLUI_IMAGEM_MODULO = -205, ERRO_EXCLUI_IMAGEM_NOME_TAMANHO = -206, ERRO_EXCLUI_IMAGEM_NOME_CARACTERE = -207
    }

    public enum GER_Erro_LabelFormatting
    {
        ERRO_OFFSET_LINHA = -211, ERRO_OFFSET_COLUNA = -212, ERRO_VEL_IMPRESSAO = -213, ERRO_TAM_PIXEL = -214,
        ERRO_CALOR = -215, ERRO_QTDE = -216, ERRO_CORTAR_ZERO = -217, ERRO_LOGIC_IMG_MODE = -219,
        ERRO_MIRROR = -220
    }

    public enum GER_Erro_Texto
    {
        TEXTO_ROTACAO_INVALIDA = -221, TEXTO_FONTE_INVALIDA = -222, TEXTO_MULTIPLICADOR_HORIZONTAL_INVALIDO = -223, TEXTO_MULTIPLICADOR_VERTICAL_INVALIDO = -224,
        TEXTO_COORDENADA_Y_INVALIDA = -225, TEXTO_COORDENADA_X_INVALIDA = -226, TEXTO_TEXTO_INVALIDO = -227
    }

    public enum GER_Erro_TextoASD
    {
        TEXTOASD_ROTACAO_INVALIDA = -231, TEXTOASD_MULTIPLICADOR_HORIZONTAL_INVALIDO = -232, TEXTOASD_MULTIPLICADOR_VERTICAL_INVALIDO = -233, TEXTOASD_TAMANHO_INVALIDO = -234,
        TEXTOASD_COORDENADA_Y_INVALIDA = -235, TEXTOASD_COORDENADA_X_INVALIDA = -236, TEXTOASD_TEXTO_INVALIDO = -237
    }

    public enum GER_Erro_TextoCourier
    {
        TEXTOCOURIER_ROTACAO_INVALIDA = -241, TEXTOCOURIER_MULTIPLICADOR_HORIZONTAL_INVALIDO = -242, TEXTOCOURIER_MULTIPLICADOR_VERTICAL_INVALIDO = -243, TEXTOCOURIER_SYMBOL_INVALIDO = -244,
        TEXTOCOURIER_COORDENADA_Y_INVALIDA = -245, TEXTOCOURIER_COORDENADA_X_INVALIDA = -246, TEXTOCOURIER_TEXTO_INVALIDO = -247
    }

    public enum GER_Erro_Linha { LINHA_COORDENADA_Y_INVALIDA = -251, LINHA_COORDENADA_X_INVALIDA = -252, LINHA_COMPRIMENTO_INVALIDO = -253, LINHA_ALTURA_INVALIDA = -254 }

    public enum GER_Erro_Box
    {
        BOX_COORDENADA_Y_INVALIDA = -261, BOX_COORDENADA_X_INVALIDA = -262, BOX_COMPRIMENTO_INVALIDO = -263, BOX_ALTURA_INVALIDA = -264,
        BOX_GROSSURA_BORDAS_HORIZONTAIS_INVALIDA = -265, BOX_GROSSURA_BORDAS_VERTICAIS_INVALIDA = -266
    }

    public enum GER_Erro_BarCode1D
    {
        BARCODE1D_ROTACAO_INVALIDA = -271, BARCODE1D_TIPO_INVALIDO = -272, BARCODE1D_LARGURA_BARRAS_LARGAS_INVALIDA = -273, BARCODE1D_LARGURA_BARRAS_ESTREITAS_INVALIDA = -274,
        BARCODE1D_ALTURA_INVALIDA = -275, BARCODE1D_COORDENADA_Y_INVALIDA = -276, BARCODE1D_COORDENADA_X_INVALIDA = -277, BARCODE1D_CODIGO_INVALIDO = -278,
        BARCODE1D_TAMANHO_INVALIDO = -279, BARCODE1D_CARACTERE_INVALIDO = -280
    }

    public enum GER_Erro_QRCodeAuto
    {
        QRCODEAUTO_ROTACAO_INVALIDA = -281, QRCODEAUTO_MULTIPLICADOR_INVALIDO = -282, QRCODEAUTO_COORDENADA_Y_INVALIDA = -283, QRCODEAUTO_COORDENADA_X_INVALIDA = -284,
        QRCODEAUTO_CODIGO_INVALIDO = -285
    }

    public enum GER_Erro_QRCodeManual
    {
        QRCODEMANUAL_ROTACAO_INVALIDA = -291, QRCODEMANUAL_MULTIPLICADOR_INVALIDO = -292, QRCODEMANUAL_COORDENADA_Y_INVALIDA = -293, QRCODEMANUAL_COORDENADA_X_INVALIDA = -294,
        QRCODEMANUAL_NUM_MODELO_INVALIDO = -295, QRCODEMANUAL_NVL_COR_ERRO_INVALIDO = -296, QRCODEMANUAL_NUM_MASCARA_INVALIDO = -297, QRCODEMANUAL_INPUT_INVALIDO = -298,
        QRCODEMANUAL_INPUT_CONFIG_INVALIDO = -299, QRCODEMANUAL_NUM_CHARS_8BIT_INVALIDO = -300, QRCODEMANUAL_CODIGO_INVALIDO = -301
    }

    public enum GER_Erro_MaxiCode
    {
        MAXICODE_ROTACAO_INVALIDA = -311, MAXICODE_COORDENADA_Y_INVALIDA = -312, MAXICODE_COORDENADA_X_INVALIDA = -313, MAXICODE_PRIMARY_ZIP_INVALIDO = -314,
        MAXICODE_SECONDARY_ZIP_INVALIDO = -315, MAXICODE_COUNTRY_INVALIDO = -316, MAXICODE_CLASS_OF_SERVICE_INVALIDA = -317, MAXICODE_CODIGO_INVALIDO = -318
    }

    public enum GER_Erro_DataMatrix
    {
        DATAMATRIX_ROTACAO_INVALIDA = -321, DATAMATRIX_MULTIPLICADOR_INVALIDO = -322, DATAMATRIX_COORDENADA_Y_INVALIDA = -323, DATAMATRIX_COORDENADA_X_INVALIDA = -324,
        DATAMATRIX_ROWS_INVALIDAS = -325, DATAMATRIX_COLUMNS_INVALIDAS = -326, DATAMATRIX_CODIGO_INVALIDO = -327
    }

    public enum GER_Erro_DataBar
    {
        DATABAR_ROTACAO_INVALIDA = -331, DATABAR_BAR_RATIO_INVALIDO = -332, DATABAR_ALTURA_INVALIDA = -333, DATABAR_COORDENADA_Y_INVALIDA = -334,
        DATABAR_COORDENADA_X_INVALIDA = -335, DATABAR_TIPO_INVALIDO = -336, DATABAR_PIXEL_MULTIPLIER_INVALIDO = -337, DATABAR_NUMERIC_LINEAR_DATA_TAMANHO_INVALIDO = -338,
        DATABAR_NUMERIC_LINEAR_DATA_CARACTERE_INVALIDO = -339, DATABAR_CODIGO_INVALIDO = -340
    }

    public enum GER_Erro_DataBarExpanded
    {
        DATABAREXPANDED_ROTACAO_INVALIDA = -341, DATABAREXPANDED_BAR_RATIO_INVALIDO = -342, DATABAREXPANDED_ALTURA_INVALIDA = -343, DATABAREXPANDED_COORDENADA_Y_INVALIDA = -344,
        DATABAREXPANDED_COORDENADA_X_INVALIDA = -345, DATABAREXPANDED_PIXEL_MULTIPLIER_INVALIDO = -346, DATABAREXPANDED_SEGMENTS_PER_ROW_INVALIDO = -347, DATABAREXPANDED_ALPHANUMERIC_TAMANHO_INVALIDO = -348,
        DATABAREXPANDED_ALPHANUMERIC_CARACTERE_INVALIDO = -349, DATABAREXPANDED_CODIGO_INVALIDO = -350
    }

    public enum GER_Erro_PDF417
    {
        PDF417_ROTACAO_INVALIDA = -351, PDF417_MULTIPLICADOR_HORIZONTAL_INVALIDO = -352, PDF417_MULTIPLICADOR_VERTICAL_INVALIDO = -353, PDF417_COORDENADA_Y_INVALIDA = -354,
        PDF417_COORDENADA_X_INVALIDA = -355, PDF417_TIPO_INVALIDO = -356, PDF417_SECURITY_LEVEL_INVALIDO = -357, PDF_417_ASPECT_RATIO_INVALIDO = -358,
        PDF417_ROW_NUMBER_INVALIDO = -359, PDF417_COLUMN_NUMBER_INVALIDO = -360, PDF417_CODIGO_INVALIDO = -361
    }

    public enum GER_Erro_Imagem { IMAGEM_COORDENADA_Y_INVALIDA = -371, IMAGEM_COORDENADA_X_INVALIDA = -372, IMAGEM_NOME_TAMANHO_INVALIDO = -373, IMAGEM_NOME_CARACTERE_INVALIDO = -374 }

    public enum GER_Erro_Outros { ERRO_CAMPOS_OVERFLOW = -381, ERRO_LIMPAR = -382 }

    public enum SAT_Erro_Generico
    {
        ARQUIVO_NAO_PODE_SER_ABERTO = -391, CNPJ_INVALIDO = -392, CPF_INVALIDO = -393, SIGNAC_INVALIDA = -394,
        NUMERO_CAIXA_INVALIDO = -395, ARQUIVO_NAO_ENCONTRADO = -396, NOME_DESTINARIO_INVALIDO = -397, CHAVES_CFE_INVALIDAS = -398,
        RESPOSTA_SESSAO_FISCAL_INVALIDA = -399, ERRO_CONSULTAR_SAT = -400
    }

    public enum SAT_Erro_Cupom_Cancelamento { CHAVE_CANCELAMENTO_INVALIDA = -401 }

    public enum SAT_Erro_Cupom_Venda
    {
        VERSAO_DADOS_ENT_INVALIDO = -411, IE_INVALIDO = -412, IM_INVALIDO = -413, INDRATISSQN_INVALIDO = -414,
        CREGTRIBISSQN_INVALIDO = -415
    }

    public enum SAT_Erro_Dados_Entrega
    {
        LOGRADOURO_INVALIDO = -421, NUMERO_INVALIDO = -422, COMPLEMENTO_INVALIDO = -423, BAIRRO_INVALIDO = -424,
        MUNICIPIO_INVALIDO = -425, UF_INVALIDO = -426
    }

    public enum SAT_Erro_Dados_Produto
    {
        CODIGO_PRODUTO_INVALIDO = -431, GTIN_INVALIDO = -432, DESCRICAO_PRODUTO_INVALIDA = -433, NCM_INVALIDO = -434,
        CEST_INVALIDO = -435, CFOP_INVALIDO = -436, UNIDADE_COMERCIAL_INVALIDA = -437, QUANTIDADE_COMERCIAL_INVALIDA = -438,
        VALOR_UNITARIO_INVALIDO = -439, REGRA_CALCULO_INVALIDA = -440, VALOR_DESCONTO_INVALIDO = -441, VALOR_ACRESCIMO_INVALIDO = -442,
        NUMERO_ITEM_INVALIDO = -443
    }

    public enum SAT_Erro_Dados_OBS_Fisco { IDENTIFICADOR_CAMPO_INVALIDO = -451, CONTEUDO_CAMPO_INVALIDO = -452, QUANTIDADE_ELEMENTO_EXCEDIDA = -454 }

    public enum SAT_Erro_Imposto
    {
        VITEM12741_INVALIDO = -461, ORIGEM_MERCADORIA_INVALIDA = -462, CST_INVALIDO = -463, ALIQUOTA_IMPOSTO_INVALIDA = -464,
        CSOSN_INVALIDO = -465, BASE_CALCULO_INVALIDA = -466, PERCENTUAL_ALIQUOTA_PIS_INVALIDA = -467, QUANTIDADE_VENDIDA_PIS_INVALIDA = -468,
        VALOR_ALIQUOTA_PIS_INVALIDA = -469, GRUPO_INVALIDO = -470, PERCENTUAL_ALIQUOTA_COFINS_INVALIDA = -471, QUANTIDADE_VENDIDA_COFINS_INVALIDA = -472,
        VALOR_ALIQUOTA_COFINS_INVALIDA = -473, VALOR_DEDUCOES_ISSQN_INVALIDA = -474, ALIQUOTA_ISSQN_INVALIDA = -475, CODIGO_MUNICIPIO_FATO_GERADOR_INVALIDO = -476,
        ITEM_LISTA_SERVICO_INVALIDO = -477, CODIGO_TRIBUTACAO_ISSQN_INVALIDO = -478, NATUREZA_OPERACAO_INVALIDA = -479, INDICADOR_INCETIVO_FISCAL_ISSQN_INVALIDO = -480
    }

    public enum SAT_Erro_Informacao_Adicional_Produto { INFORMACOES_ADICIONAIS_PRODUTO_INVALIDA = -491 }

    public enum SAT_Erro_Total { VALOR_DESCONTO_SUBTOTAL_INVALIDO = -501, VALOR_ACRESCIMO_SUBTOTAL_INVALIDO = -502, VALOR_VCFELEI12741_INVALIDO = -503 }

    public enum SAT_Erro_Pagamento { CODIGO_MEIO_PAGAMENTO_INVALIDO = -511, VALOR_MEIO_PAGAMENTO_INVALIDO = -512, CREDENCIADORA_CARTAO_INVALIDO = -513, QUANTIDADE_MEIO_PAGAMENTO_EXCEDIDA = -514 }

    public enum SAT_Erro_Informacao_Adicional { TAMANHO_INFORMACOES_COMPLEMENTARES_INVALIDO = -521 }

    public enum NFCE_Erro_Impostos
    {
        NFCE_TOTAL_TRIBUTOS_INVALIDO = -700, NFCE_CST_INVALIDO = -701, NFCE_VBC_INVALIDO = -702, NFCE_ALIQUOTA_IMPOSTO_INVALIDA = -703,
        NFCE_VALOR_IMPOSTO_INVALIDO = -704, NFCE_QBCPROD_INVALIDA = -705, NFCE_VALOR_ALIQUOTA_PISCOFINS_INVALIDA = -706, NFCE_CODIGO_MUNICIPIO_FATO_GERADOR_ISSQN_INVALIDO = -707,
        NFCE_ITEM_SERVICO_INVALIDO = -708, NFCE_VALOR_DEDUCAO_ISSQN_INVALIDO = -709, NFCE_VOUTRO_ISSQN_INVALIDO = -710, NFCE_VALOR_DESCONTO_INCONDICIONADO_INVALIDO = -711,
        NFCE_VALOR_DESCONTO_CONDICIONADO_INVALIDO = -712, NFCE_VALOR_REDENCAO_ISS_INVALIDO = -713, NFCE_INDICADOR_EXIGIBILIDADE_ISS_INVALIDO = -714, NFCE_CODIGO_SERVICO_ISSQN_INVALIDO = -715,
        NFCE_CODIGO_MUNICIPIO_ISSQN_INVALIDO = -716, NFCE_CODIGO_PAIS_ISSQN_INVALIDO = -717, NFCE_NUMERO_PROCESSO_INVALIDO = -718, NFCE_INDICADOR_INCENTIVO_FISCAL = -719,
        NFCE_IPI_CLASSE_ENQUADRAMENTO_INVALIDA = -720, NFCE_IPI_CNPJ_PRODUTO_INVALIDO = -721, NFCE_IPI_CODIGO_SELO_INVALIDO = -722, NFCE_IPI_QUANTIDADE_SELO_INVALIDO = -723,
        NFCE_IPI_CODIGO_ENQUADRAMENTO_INVALIDO = -724, NFCE_IPI_QUANTIDADE_TOTAL_TRIBUTACAO_INVALIDA = -725, NFCE_IPI_VALOR_UNIDADE_TRIBUTAVEL_INVALIDA = -726, NFCE_II_VALOR_DESPESAS_ADUANEIRAS_INVALIDO = -727,
        NFCE_II_VALOR_IOF_INVALIDO = -728, NFCE_ICMS_N11_ORIG_INVALIDA = -729, NFCE_ICMS_N13_MODBC_INVALIDA = -730, NFCE_ICMS_N14_PREDBC_INVALIDO = -731,
        NFCE_ICMS_N16_PICMS_INVALIDO = -732, NFCE_ICMS_N16A_VICMSOP_INVALIDO = -733, NFCE_ICMS_N16B_PDIF_INVALIDO = -734, NFCE_ICMS_N17_VICMS_INVALIDO = -735,
        NFCE_ICMS_N17a_VBCFCP_INVALIDO = -736, NFCE_ICMS_N17b_PFCP_INVALIDO = -737, NFCE_ICMS_N17c_VFCP_INVALIDO = -738, NFCE_ICMS_N18_MODBCST_INVALIDO = -739,
        NFCE_ICMS_N19_PMVAST_INVALIDO = -740, NFCE_ICMS_N20_PREDBCST_INVALIDO = -741, NFCE_ICMS_N21_VBCST_INVALIDO = -742, NFCE_ICMS_N22_PICMSST_INVALIDO = -743,
        NFCE_ICMS_N23_VICMSST_INVALIDO = -744, NFCE_ICMS_N27A_VICMSDESON_INVALIDO = -745, NFCE_ICMS_N28_MOTDESICMS_INVALIDO = -746, NFCE_ICMS_N26_VBCSTRET_INVALIDO = -747,
        NFCE_ICMS_N26a_PST_INVALIDO = -748, NFCE_ICMS_N26b_VICMSSUBUSTITUTO_INVALIDO = -749, NFCE_ICMS_N25_PBCOP_INVALIDO = -750, NFCE_ICMS_N24_UFST_INVALIDO = -751,
        NFCE_ICMS_N27_VICMSSTRET_INVALIDO = -752, NFCE_ICMS_N27a_NFCE_ICMS_N27_INVALIDO = -753, NFCE_ICMS_N27b_PFCPSTRET_INVALIDO = -754, NFCE_ICMS_N27d_VFCPSTRET_INVALIDO = -755,
        NFCE_ICMS_N31_VBCSTDEST_INVALIDO = -755, NFCE_ICMS_N32_VICMSSTDEST_INVALIDO = -756, NFCE_ICMS_N12A_CSOSN_INVALIDO = -757, NFCE_ICMS_N29_PCREDSN_INVALIDO = -758,
        NFCE_ICMS_N30_VCREDICMSSN_INVALIDO = -759, NFCE_ICMS_N34_PREDBCEFET_INVALIDO = -760, NFCE_ICMS_N35_VBCEFET_INVALIDO = -761, NFCE_ICMS_N36_PICMSEFET_INVALIDO = -761,
        NFCE_ICMS_N37_VICMSEFET_INVALIDO = -762
    }

    public enum Bal_Erro_Balanca { BAL_CONEXAO_ATIVA = -791, BAL_BALANCA_EM_USO = -792, BAL_BALANCA_INVALIDA = -793, BAL_NENHUMA_BALANCA_EM_USO = -794 }

    public enum Bal_Erro_Protocolo
    {
        BAL_PROTOCOLO_INVALIDO = -801, BAL_PROTOCOLO_EM_USO = -802, BAL_PROTOCOLO_NAO_SUPORTADO = -803, BAL_PROTOCOLO_NAO_SUPORTADO_PELAS_CONFIGS_SERIAIS = -804,
        BAL_NENHUM_PROTOCOLO_EM_USO = -805
    }

    public enum Bal_Erro_Abertura
    {
        BAL_BAUDRATE_NAO_SUPORTADO = -811, BAL_LENGTH_NAO_SUPORTADO = -812, BAL_PARITY_NAO_SUPORTADO = -813, BAL_STOPBITS_NAO_SUPORTADO = -814,
        BAL_BAUDRATE_INVALIDO = -815, BAL_LENGTH_INVALIDO = -816, BAL_PARITY_INVALIDO = -817, BAL_STOPBITS_INVALIDO = -818,
        BAL_COMBINACAO_DE_PARAMETROS_INVALIDA = -819, BAL_CONFIGS_SERIAIS_NAO_SUPORTADAS_PELO_PROTOCOLO = -820
    }

    public enum Bal_Erro_Outros
    {
        BAL_QTD_LEITURAS_INVALIDA = -821, BAL_COMANDO_NAO_SUPORTADO_PELA_BALANCA = -822, BAL_COMANDO_NAO_SUPORTADO_PELO_PROTOCOLO = -823, BAL_PRECO_INVALIDO = -824,
        BAL_FALHA_NA_LEITURA_DO_PESO = -825, BAL_FALHA_AO_ENVIAR_PRECO = -826, CHAMADA_NAO_PERMITIDA = -827
    }

    public enum PDF_Error
    {
        ZINT_NAO_CARREGADA = -890, ARQUIVO_NAO_FOI_ABERTO = -891, DIRETORIO_INVALIDO = -892, IMPRESSORA_NAO_E_VALIDA = -893,
        FALHA_AO_CARREGAR_DOCUMENTO = -894, DOCUMENTO_NAO_EXISTE = -895, DOCUMENTO_NAO_POSSUI_PAGINAS = -896, IMAGEM_NAO_FOI_GERADA = -897
    }

    public enum Br_Erro_Config
    {
        BR_IP_TERMINAL_INVALIDO = -1201, BR_PORTA_TRANSACAO_INVALIDA = -1202, BR_PORTA_STATUS_INVALIDA = -1203, BR_PORTAS_IGUAIS = -1204,
        BR_TIMEOUT_INVALIDO = -1205, BR_IP_TERMINAL_NAO_INFORMADO = -1206, BR_SENHA_NULL = -1207, BR_SENHA_NAO_INFORMADA = -1208,
        BR_MESMA_CONFIG_SENHA = -1209
    }

    public enum Br_Erro_Param
    {
        BR_VALOR_TOTAL_NULL = -1211, BR_VALOR_TOTAL_NAN = -1212, BR_VALOR_TOTAL_INVALIDO = -1213, BR_TIPO_CARTAO_INVALIDO = -1214,
        BR_TIPO_FINANCIAMENTO_INVALIDO = -1215, BR_NUM_PARCELAS_INVALIDO = -1216, BR_NSU_NULL = -1217, BR_NSU_INVALIDO = -1218,
        BR_DATA_HORA_NULL = -1219, BR_DATA_HORA_INVALIDA = -1220, BR_OPERACAO_INVALIDA = -1221, BR_ERRO_ABERTURA_ARQUIVO = -1222,
        BR_ERRO_ESCREVER_ARQUIVO = -1223, BR_OUTPUT_NULL = -1224, BR_ID_TRANSACAO_INVALIDO = -1225, BR_PDV_NULL = -1226,
        BR_PDV_INVALIDO = -1227, BR_TIPO_CUPOM_INVALIDO = -1228, BR_XML_NULL = -1229, BR_XML_INVALIDO = -1230
    }

    public enum Br_Erro_Status { BR_STATUS_EM_ANDAMENTO = -1231, BR_ERRO_CONECTAR_STATUS = -1232, BR_ERRO_LEITURA_STATUS = -1233, BR_STATUS_NAO_RETORNADO = -1234 }

    public enum Br_Erro_Transacao
    {
        BR_TRANSACAO_EM_ANDAMENTO = -1241, BR_ERRO_CONECTAR_TRANSACAO = -1242, BR_ERRO_ENVIO_TRANSACAO = -1243, BR_ERRO_CONFIRMAR_TRANSACAO = -1244,
        BR_ERRO_LEITURA_TRANSACAO = -1245, BR_TRANSACAO_NAO_RETORNADA = -1246, BR_TELA_BLOQUEADA = -1247
    }

    public enum Br_Erro_Param_Extras
    {
        BR_ASS_QRCODE_NULL = -1251, BR_ASS_QRCODE_INVALIDO = -1252, BR_CSC_NULL = -1253, BR_CSC_INVALIDO = -1254,
        BR_PARAMETRO_NULL = -1255, BR_PARAMETRO_INVALIDO = -1256
    }

    public enum UTIL_Erro_Interno
    {
        UTIL_DATA_INVALIDA = -9000, UTIL_ERRO_CAMINHO_ABSOLUTO = -9001, UTIL_EXTENSAO_INVALIDA = -9002, UTIL_TIPO_INVALIDO = -9003,
        UTIL_ERRO_GERAR_ESTRUTURA = -9004, UTIL_ERRO_ACESSAR_ESTRUTURA = -9005
    }

    public enum Codigos_Gerais
    {
        SUCESSO = 0,
        ERRO_DESCONHECIDO = -9999
    }
}